receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'dcgm-exporter'
          static_configs:
            - targets: ['dcgm-exporter-svc.default.svc.cluster.local:9400']
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default


service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]