global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector.default.svc.cluster.local:8889']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']